server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    
    # Log error dan akses Nginx
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    
    # Pintu gerbang utama Laravel WAJIB mengarah ke folder public/
    root /app/public;

    # URL Routing ala Laravel (Biar URL cantik lu jalan semua)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Lempar pemrosesan file .php ke container "app" (PHP-FPM)
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # "app" ini merujuk ke nama service PHP di docker-compose.yml lu
        fastcgi_pass app:9000; 
        
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Sembunyikan file dot (kayak .env atau .git) dari akses publik
    location ~ /\.ht {
        deny all;
    }
}